#pragma once
#include <string>

/*
 * On choices
 * - Why Policy constructor accepts the client_uuid?
 *   Because the responsibility to resolve the client_email -> client_uuid
 *   mapping lies with the policyService, the policy itself needs only to
 *   create its own uuid.
 */

namespace insura::domain {
/* TODO: evaluate policy deduplication strategy. Currently no mechanism
 * prevents adding duplicate policies (same type, client, start date).
 * Options to consider at end-of-project polish:
 * 1. Compare type + client_uuid + start_date on add
 * 2. Add a human-readable policy number (auto-generated, persisted,
 *    counter derived from highest existing number on load)
 * 3. Accept duplicates as valid (user corrects manually)
 * Decision deferred: current scope assumes no accidental duplicates. */
class Policy {
 public:
  enum class PolicyStatus {
    ACTIVE,
    EXPIRED,
    CANCELLED,
    PENDING,
  };

  enum class PolicyType {
    AUTO,
    LIFE,
    HEALTH,
    HOME,
  };

  Policy(std::string client_uuid, PolicyType policy_type,
         std::string start_date, std::optional<std::string> end_date,
         double amount, PolicyStatus policy_status,
         std::optional<std::string> notes);

  const std::string& getUuid() const;
  const std::string& getClientUuid() const;
  const std::string& getNumber() const;
  const std::string& getType() const;
  const PolicyStatus getStatus() const;
  // I should add others but for now is ok

 private:
  std::string uuid_;
  std::string client_uuid_;
  PolicyType policy_type_;
  PolicyStatus policy_status_;

  std::string start_date_;  // generated by constructor, decide the type
  std::optional<std::string> end_date_;    // optional and I should decide the type

  double amount_;
  std::optional<std::string> notes_;
  std::string
      created_at_;  // re-considere type and also naming (e.g. created_time)
  std::string updated_at_;
};

}  // namespace insura::domain
