#pragma once
#include <string>

/*
 * On choices
 * - Why Policy constructor accepts the client_uuid?
 *   Because the responsibility to resolve the client_email -> client_uuid
 *   mapping lies with the policyService, the policy itself needs only to
 *   create its own uuid.
 */

namespace insura::domain {

class Policy {
 public:
  enum class PolicyStatus {
    ACTIVE,
    EXPIRED,
    CANCELLED,
    PENDING,
  };

  /* To understand which fields require a getter, I should decide what
   * informations are needed
   * E.g. uuid and client_uuid are only for my operations
   * I mean, do I really need getter and setter?
   * */

  /* The Policy constructor needs the client, type, status, start date
   * and maybe the end date
   * - Client just to retrieve the uuid, I think the email could be
   *   the right field to be associated
   *
   * */
  Policy(std::string client_uuid, std::string policy_type,
         std::string start_date);

  const std::string& getUuid() const;
  const std::string& getClientUuid() const;
  const std::string& getNumber() const;
  const std::string& getType() const;
  const PolicyStatus getStatus() const;
  // I should add others but for now is ok

 private:
  std::string uuid_;
  std::string client_uuid_;
  std::string policy_number_;
  std::string policy_type_;
  PolicyStatus policy_status_;

  std::string start_date_;  // generated by constructor, decide the type
  std::string end_date_;    // optional and I should decide the type

  double premium_;
  std::string notes_;
  std::string
      created_at_;  // re-considere type and also naming (e.g. created_time)
  std::string updated_at_;
};

}  // namespace insura::domain
